services:
  minio:
    build:
      context: ./data/s3
      dockerfile: Dockerfile
    tty: true
    image: pet-bit-melody-minio
    container_name: pbm-minio
    restart: always
    env_file:
      - ./data/s3/.env
    ports:
      - "9000:9000"
      -  "9001:9001"
    volumes:
      - ./data/s3/cache:/data
    command: server /data --console-address ":9001"
    networks:
      - pbm-network

  mariadb:
    build:
      context: ./data/db
      dockerfile: Dockerfile
    image: pet-bit-melody-mariadb
    container_name: pbm-mariadb
    restart: always
    env_file:
      - ./data/db/.env
    ports:
      - "3307:3306"
    volumes:
      - ./data/db/cache:/var/lib/mysql
    depends_on:
      - minio
    networks:
      - pbm-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: pet-bit-melody-server
    container_name: pbm-server
    restart: always
    tty: true
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    volumes:
      - ./server/:/srv/
    depends_on:
      - maria-db
    networks:
      - pbm-network

  web:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: pet-bit-melody-web
    container_name: pbm-web
    restart: always
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - server
    networks:
      - pbm-network

networks:
  pbm-network:
    driver: bridge
