FROM mariadb:latest

ENV LOCATION=docker-db

# Deploy databases from .sql files
COPY ./data/ /docker-entrypoint-initdb.d/

# Listing the content of the app and docker-entrypoint-initdb.d folders
RUN echo "Content of /docker-entrypoint-initdb.d/:" && ls -a /docker-entrypoint-initdb.d/

# Make port 3300-3309 available to the world outside this container
EXPOSE 3300-3309
